apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: busybox-httpd
  namespace: default
spec:
  rules:
  - host: kickstart.pik8s.home
    http:
      paths:
      - backend:
          serviceName: busybox-httpd
          servicePort: 8088
