apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-httpd
  name: busybox-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-httpd
  template:
    metadata:
      labels:
        app: busybox-httpd
    spec:
      containers:
      - image:  busybox
        command:
          - httpd
        args: ["-v","-f","-p","0.0.0.0:8088","-h","/var/www/html","-c","/var/www/html/httpd.conf"]
        imagePullPolicy: IfNotPresent
        name: busybox-httpd
        volumeMounts:
        - mountPath: /var/www/html
          name: tftpboot

      nodeSelector:
        kubernetes.io/arch: arm
#        kubernetes.io/arch: amd64
      restartPolicy: Always
#      restartPolicy: Always
      volumes:
      - name: tftpboot
        nfs:
          path: /mnt/nfs/pvdata/tftpboot/kickstart
          server: nfs.home
